mode = "dark"
accent = "#DCCDAA"
selection = "#354E4B"
selection_foreground = "#F2E9D0"
selection_background = "#354E4B"
muted = "#A7AB99"
background = "#10262B"
dark_background = "#0B1E23"
darker_background = "#07171B"
lighter_background = "#20383C"
foreground = "#E4DBBF"
dark_foreground = "#A7AB99"
light_foreground = "#C4C4AC"
bright_foreground = "#F2E9D0"
hyprland_active_border = "#DCCDAA"
hyprland_inactive_border = "#3D5958"
red = "#E4DBBF"
green = "#DCCDAA"
yellow = "#C4C4AC"
orange = "#C4C4AC"
blue = "#DCCDAA"
magenta = "#E4DBBF"
cyan = "#A7AB99"
brown = "#A7AB99"
bright_red = "#F2E9D0"
bright_green = "#E4DBBF"
bright_yellow = "#F2E9D0"
bright_blue = "#C4C4AC"
bright_magenta = "#E4DBBF"
bright_cyan = "#DCCDAA"
